
[build]
  publish = "dist"
  command = "npm run build"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proper MIME type configuration for JavaScript modules
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

# Note: Environment variables should be set in the Netlify dashboard
# These placeholders will be overridden by the values in the dashboard
[build.environment]
  VITE_SUPABASE_URL = "placeholder"
  VITE_SUPABASE_ANON_KEY = "placeholder"
  VITE_STRIPE_PUBLIC_KEY = "placeholder"
